#Set a default branch
# set migration command, but only run them when â€“migrate is specified

environments:
  production:
    branch: idea
    migrate: false
    migration_command: bundle exec rake db:migrate 
    maintenance_on_migrate: true
    precompile_assets: true
    